import Link from "next/link";
import { LockKeyhole } from "lucide-react";
import { notFound } from "next/navigation";
import { requireAdmin } from "@/lib/admin";
import { createServiceClient } from "@/lib/supabase/service";
import { ModerationActionPanel } from "@/components/moderation/ModerationActionPanel";

export default async function ModerationCasePage({ params }: { params: Promise<{ caseId: string }> }) {
  await requireAdmin(); const { caseId } = await params; const db = createServiceClient(); const [{ data: item }, { data: events }] = await Promise.all([db.from("moderation_cases").select("id,status,severity,target_type,target_id,cookbook_id,target_owner_user_id,reason_code,reporter_statement,assigned_to_admin_id,decision,opened_at,resolved_at").eq("id", caseId).maybeSingle(), db.from("moderation_case_events").select("id,event_type,reason_code,safe_metadata_json,created_at").eq("case_id", caseId).order("created_at")]);
  if (!item) notFound(); const critical = item.status === "critical_sensitive";
  return <main className="app-paper-bg min-h-screen px-5 py-8"><div className="mx-auto max-w-3xl"><Link href="/app/admin/moderation" className="text-sm font-bold text-green-deep hover:underline">Back to moderation queue</Link><div className="mt-5 rounded-md border border-line-soft bg-card p-6"><div className="flex items-center gap-2"><LockKeyhole size={20} className={critical ? "text-danger" : "text-green-deep"} /><h1 className="text-2xl font-black text-ink">Case {item.id.slice(0, 8)}</h1></div><p className="mt-3 text-sm text-ink-muted">{item.severity} severity · {item.status} · {item.target_type} · reason: {item.reason_code.replaceAll("_", " ")}</p>{critical ? <p className="mt-4 rounded-sm bg-danger/10 p-3 text-sm text-danger">Critical-sensitive: no preview or original is available. Follow the counsel/provider-approved incident procedure before enabling this category in production.</p> : <><p className="mt-4 text-sm text-ink-muted">No original file, storage path, raw recipe content, email address, or reporter identity is shown in this case view.</p>{item.reporter_statement && <p className="mt-3 rounded-sm bg-green-pale p-3 text-sm text-ink">Reporter statement: {item.reporter_statement}</p>}</>}</div>{!critical && <div className="mt-5"><ModerationActionPanel caseId={item.id} targetType={item.target_type} /></div>}<section className="mt-5 rounded-md border border-line-soft bg-card p-5"><h2 className="font-black text-ink">Case timeline</h2><div className="mt-3 space-y-3">{(events ?? []).map((event) => <div key={event.id} className="border-l-2 border-green-sage pl-3"><p className="text-sm font-bold text-ink">{event.event_type.replaceAll("_", " ")}</p><p className="text-xs text-ink-soft">{new Date(event.created_at).toLocaleString()} {event.reason_code ? `· ${event.reason_code.replaceAll("_", " ")}` : ""}</p></div>)}</div></section></div></main>;
}
